Repository RockySingh137/Amazon-Clone, pull requests merged in 2022-10, with the labels that each got.

#3 header file for amazon website added
  client/package-lock.json
  client/package.json
  client/public/amazon_PNG25.png
  client/src/components/header/Navbar.js
  client/src/components/header/navbar.css
  client/src/components/newnavbar/Newnav.js
  client/src/components/newnavbar/newnav.css
Labels: good first issue, Approved

#4 added components for home
  client/public/nav.jpg
  client/src/App.css
  client/src/App.js
  client/src/components/home/Banner.js
  client/src/components/home/Maincomp.js
  client/src/components/home/Slide.js
  client/src/components/home/banner.css
  client/src/components/home/home.css
  client/src/components/newnavbar/Newnav.js
  client/src/components/newnavbar/newnav.css
Labels: Hacktoberfest-accepted, Hacktoberfest, Approved

#5 Product data
  client/package-lock.json
  client/package.json
  client/src/components/home/Banner.js
  client/src/components/home/banner.css
  client/src/components/home/productdata.js
Labels: Approved

#6 multi carousel added
  client/package-lock.json
  client/package.json
  client/src/components/home/Maincomp.js
  client/src/components/home/Slide.js
Labels: Approved

#7 css added for slide
  client/src/components/home/Slide.js
  client/src/components/home/slide.css
Labels: Approved

#8 added js for footer
  client/src/components/footer/Footer.js
  client/src/components/footer/footer.css
  client/src/components/home/Maincomp.js
  client/src/components/home/Slide.js
  client/src/components/home/slide.css
Labels: Approved

#9 css for home
  client/src/components/footer/footer.css
Labels: documentation, Approved

#10 added sign in and routing
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/footer/Footer.js
  client/src/components/footer/footer.css
  client/src/components/signup_signin/Sign_in.js
  client/src/components/signup_signin/Sign_up.js
  client/src/index.js
Labels: Approved

#11 CSS styling for sign in sign up
  client/src/components/signup_signin/signup.css
Labels: Approved

#12 added sign up page
  client/public/blacklogoamazon.png
  client/src/components/signup_signin/Sign_in.js
  client/src/components/signup_signin/Sign_up.js
  client/src/components/signup_signin/signup.css
Labels: Approved

#13 fixed bugs in sign up
  client/src/components/signup_signin/Sign_up.js
Labels: documentation, Approved

#14 css for cart
  client/src/components/cart/Cart.js
  client/src/components/cart/cart.css
  client/src/components/header/Navbar.js
  client/src/components/signup_signin/Sign_in.js
  client/src/components/signup_signin/Sign_up.js
  client/src/components/signup_signin/signup.css
Labels: Approved

#15 more css added for cart
  client/src/components/cart/cart.css
Labels: Approved

#16 Js for cart
  client/src/components/cart/Cart.js
Labels: Approved

#17 cart items
  client/src/components/cart/Cart.js
Labels: enhancement, Approved

#18 use effect added
  client/src/components/cart/Cart.js
Labels: Approved

#19 fixed cart js bugs
  client/src/components/cart/Cart.js
Labels: Approved

#20 buynow css added
  client/src/components/buynow/buynow.css
Labels: Approved

#21 buynow js added
  client/src/components/buynow/Buynow.js
Labels: Approved

#22 added more js for buynow
  client/src/components/buynow/Buynow.js
Labels: documentation, Approved

#23 js for empty cart
  client/src/components/buynow/Empty.js
Labels: Approved

#25 added more css for buynow
  client/src/components/buynow/buynow.css
Labels: Approved

#26 option js
  client/src/components/buynow/Option.js
Labels: Approved

#27 right.js
  client/src/components/buynow/Right.js
Labels: Approved

#28 subtotal added
  client/src/components/buynow/Subtotal.js
Labels: Approved

#29 added context
  client/src/components/context/Context.js
Labels: Approved
